### ISSUE TITLE
Include a toggle switch component

### ISSUE THREAD

**Issue by rich29d** [vitta-health/Vi-Ui#16]
**Is your feature request related to a problem? Please describe.**
It would be nice if there was also a component where the user could turn on / off, the checkbox is useful, but his intention is more to select items than to switch on / off.

**Describe the solution you'd like**
The idea is simply a checkbox but with a different style so that it fails to understand that this item is actually enabled or not.

**Comment by jessicamrbr** [comment]
#25

**Comment by jessicamrbr** [comment]
#25
