### ISSUE TITLE
Vi-Select dropdown overlaps spinner

### ISSUE THREAD

**Issue by luizzzdev** [vitta-health/Vi-Ui#34]
**Describe the bug**
When Vi-Select is loading and the spinner is shown, the dropdown arrow overlaps the spinner.

**To Reproduce**
1. Enter in Vi-Select field
2. Type something
3. Make him load and show the spinner

**Expected behavior**
The dropdown arrow should disappear

**Screenshots**
![viselect](https://user-images.githubusercontent.com/33661847/49238952-b639be80-f3e8-11e8-8347-6e3b6afd2bfb.png)

**Desktop (please complete the following information):**
 - OS: [ Linux Ubuntu 18.10 ]
 - Browser [ chrome, firefox ]
 - Version [ 70.0.3538.102, 63.0 ]

**Comment by taciomedeiros** [comment]
@luizzzdev já esta trabalhando nesta?

**Comment by luizzzdev** [comment]
@taciomedeiros eu lembro de já ter feito essa issue na verdade :thinking: 

Mais tarde dou uma conferida aqui!

**Comment by luizzzdev** [comment]
Closed on #41
