### ISSUE TITLE
Problem tooltip watch context

### ISSUE THREAD

**Issue by faelribeiro22** [vitta-health/Vi-Ui#38]
The contents of the tooltip do not update. 
I sent the value of a computed to the prop of the tooltip, and it did not update.

**Comment by luizzzdev** [comment]
@taciomedeiros @beeblebrox3 @jeancarlos I couldn't reproduce, the snippet I used to test is below, should we close due to lack of proves ?
![tooltip_gif](https://user-images.githubusercontent.com/33661847/66177160-c0df6880-e636-11e9-9be1-a324482fd59e.gif)

**Comment by beeblebrox3** [comment]
@luizzzdev  agreed
