### ISSUE TITLE
ViToggle may be misleading

### ISSUE THREAD

**Issue by beeblebrox3** [vitta-health/Vi-Ui#47]
ViToggle when disable has an green circle that can be confusing for users on bad displays:

![WhatsApp Image 2019-05-17 at 16 11 17](https://user-images.githubusercontent.com/767624/57950804-ac384900-78be-11e9-9c02-99ccd8135cd3.jpeg)

**Comment by taciomedeiros** [comment]
What is the best way to handle that? I think a shadow could be great in this case. What do you think @pablovieiras @jeancarlos

**Comment by jeancarlos** [comment]
@taciomedeiros this would be the only component with a shadow. I will see what could be done and answer here.

**Comment by pablovieiras** [comment]
@taciomedeiros I think we could whether put an opacity (like material design does) or change it to grey shades

**Comment by beeblebrox3** [comment]
I think we need to remove the green when it is off. Green for "on", _no green_ for "off".

Like iOS: 
![image](https://user-images.githubusercontent.com/767624/65612560-dc89a580-df8a-11e9-9ae6-fdcf94bd5566.png)
https://developer.apple.com/design/human-interface-guidelines/ios/controls/switches/

Or Android:
![image](https://user-images.githubusercontent.com/767624/65612885-718c9e80-df8b-11e9-90a7-30727d828b87.png)
https://material.io/components/selection-controls/#

**Comment by jeancarlos** [comment]
My approach would be more like IOs. I think Material still leave margin for confusion.

**Comment by pablovieiras** [comment]
I thought the problem was with the disabled state. Now, since we're discussing about the on/off state, I totally agree with Luis :)
