### ISSUE TITLE
Problema quando não informar o total de registros no componente paginação

### ISSUE THREAD

**Issue by ricardoalvarenga101** [vitta-health/Vi-Ui#5]
**Describe the bug**
Quando não informamos o total de registros a paginação corre infinitamente, até ai td certo. O problema eh que ela continua mesmo quando termina os registros. Seria interessante verificar se a quantidade de registros é inferior ao total por paginas, assim sabemos que os registros acabaram e nao precisa habilitar o next page ;)

**Comment by jeancarlos** [comment]
Boa, se tiver disposto a fazer o PR já que tu é pai do componente, fica a vontade. Estou meio corrido de coisas pra fazer.

**Comment by jeancarlos** [comment]
Closing the issue. @ricardoalvarenga101 please, fill the specified fields on the bug report template and post it again (or edit this post). In english possibly. We don't have a big community helping it yet, but it's good to keep or standards in check.
