### ISSUE TITLE
Project development environment is broken

### ISSUE THREAD

**Issue by luizzzdev** [vitta-health/Vi-Ui#64]
**Describe the bug**
When I run the project using the command "npm run styleguide", I get the following error:

![image](https://user-images.githubusercontent.com/33661847/66950179-477c4880-f02e-11e9-80ce-a17cf9c104b1.png)

**To Reproduce**
1. Run "npm run styleguide"

**Expected behavior**
The project should run and open the documentation

**Comment by jeancarlos** [comment]
Solved in #65
