### ISSUE TITLE
Tests for ViAlert Component

### ISSUE THREAD

**Issue by taciomedeiros** [vitta-health/Vi-Ui#70]
**Is your feature request related to a problem? Please describe.**
This Issue consists in cover the ViAlert component with tests

**Describe the solution you'd like**
Create tests for testing the above features

- colors
- formats
- state
- event behaviours

**Additional context**

- [ ] colors
- [ ] formats
- [ ] state
- [ ] event behaviours

**Comment by luizzzdev** [comment]
@taciomedeiros  I'm on it!

**Comment by luizzzdev** [comment]
Fixed on: https://github.com/vitta-health/Vi-Ui/pull/71
Closing this issue.
